language: generic

matrix:
    include:
      - os: linux
        dist: xenial
        env:
           - TRAVIS_PYTHON_VERSION=3.6
      - os: linux
        dist: xenial
        env:
           - TRAVIS_PYTHON_VERSION=2.7

notifications:
    email:
      - bespin@physik.uni-bonn.de

cache:
    directories:
      - $HOME/.pip-cache/

# Setup miniconda python with needed packages
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINICONDA_OS=Linux ;
      else
        MINICONDA_OS=MacOSX ;
    fi ;

install:
    # Install verilog compiler for simulation
  - sudo apt-get install gperf
  - git clone https://github.com/steveicarus/iverilog.git
  - cd iverilog && autoconf && ./configure && make && sudo make install && cd ..    

    # Install python
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh ;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh ;
    fi;
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

    # Install dependencies
  - conda install --yes pip numba numpy pytables pyyaml scipy tqdm matplotlib pytest
  - pip install --upgrade pip
  - pip install coverage python-coveralls pixel_clusterizer pylandau cocotb==1.0.dev3

    # Install basil
  - git clone -b development https://github.com/SiLab-Bonn/basil; cd basil; python setup.py develop; cd ..;

    # Install tjmonopix-daq
  - python setup.py develop
  - printenv | sort

  #- pip install --upgrade pip
  #- pip install coverage python-coveralls

# Run test
script:
  # Hack to allow tests coverage in multi processes, http://coverage.readthedocs.org/en/latest/subprocess.html
  # - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  #- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #    touch $HOME/miniconda/lib/python2.7/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python2.7/site-packages/converage.pth;
  #  else
  #    touch $HOME/miniconda/lib/python3.6/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python3.6/site-packages/converage.pth;
  #  fi
  - cd tests; travis_wait 5 py.test -s
 
# after_success:
#   - coveralls --data_file .coverage.*
#   - scripts/create_doc.sh
